# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Restore NuGet packages
      run: msbuild /t:restore YourSolution.sln
    - name: Build
      run: msbuild OutlookFormFinder.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: bin\Release\*


   
